import turtle
turtle.pencolor("black") 
turtle.fillcolor("white")#宝可梦球下半部轮廓
turtle.penup()
turtle.goto(-100,-2)
turtle.begin_fill()
turtle.pendown()
turtle.seth(270)
turtle.circle(100,180)
turtle.seth(180)
turtle.fd(70)
turtle.seth(-90)
turtle.circle(-30,180)
turtle.seth(-180)
turtle.fd(70)
turtle.end_fill()

turtle.fillcolor("red")#宝可梦球下半部上半部轮廓
turtle.begin_fill()
turtle.penup()
turtle.goto(-100,2)
turtle.pendown()
turtle.seth(0)
turtle.fd(70)
turtle.seth(90)
turtle.circle(-30,180)
turtle.seth(0)
turtle.fd(70)
turtle.seth(90)
turtle.circle(100,180)
turtle.end_fill()



turtle.fillcolor("grey")#宝可梦球中部
turtle.begin_fill()
turtle.penup()
turtle.goto(100,-2)
turtle.pendown()
turtle.seth(180)
turtle.fd(70)
turtle.seth(-90)
turtle.circle(-30,180)
turtle.seth(-180)
turtle.fd(70)
turtle.goto(-100,2)
turtle.seth(0)
turtle.fd(70)
turtle.seth(90)
turtle.circle(-30,180)
turtle.seth(0)
turtle.fd(70)
turtle.goto(100,-2)
turtle.end_fill()

turtle.fillcolor("white")#宝可梦球中部按键
turtle.begin_fill()
turtle.penup()
turtle.goto(-20,0)
turtle.pendown()
turtle.seth(-90)
turtle.circle(20)
turtle.end_fill()
turtle.penup()
turtle.goto(-10,0)
turtle.pendown()
turtle.seth(-90)
turtle.circle(10)

turtle.hideturtle()
turtle.done()